### ISSUE TITLE
Request: Update Tags/Releases feature for repository

### ISSUE THREAD

**Issue by seangwright** [pimbrouwers/Falco#103]
The [latest version of the library is 4.0.3 on NuGet](https://www.nuget.org/packages/Falco#versions-body-tab), but [the latest tag/release on GitHub is 3.1](https://github.com/pimbrouwers/Falco/releases/)

![screenshot of releases page](https://user-images.githubusercontent.com/1382768/210192896-1f5ec8c6-ef44-40c3-ac9f-6e839c7896b6.png)

Since there's no [CHANGELOG.md](https://github.com/olivierlacan/keep-a-changelog/blob/main/CHANGELOG.md) in the repository, it can be confusing trying to identify

1. What has changed between versions
2. What the latest official released version from the repository code main/master branch is

The [Releases page](https://github.com/pimbrouwers/Falco/releases/) for the repository is commonly used to help developers understand when new releases and what the changes were for each version. It can be really helpful for new developers trying to orient themselves in the repository/versioning history.

Could the Releases/Tags be updated for Falco to reflect that 4.0.3 is the latest and what changes are in it since 3.1 (even if you just summarize the changes).

Thanks!

**Comment by pimbrouwers** [comment]
I apologize Sean. I recognize that I am not using that feature correctly, or providing an appropriate alternative. My time on this lately has been very sporadic and limited, so I've tried to pick and choose the places I want to focus on. 

Documentation is a ton of work, and I'll admit that I could do a better job. This will be my next focus.

**Comment by pimbrouwers** [comment]
I have gone back and review the entire commit history and created a [changelog](https://github.com/pimbrouwers/Falco/blob/master/CHANGELOG.md). 

I really like the simplicity of the approach, certainly much easier to maintain. I will extract some of the useful information from the existing release notes, and create migration documents within the `documentation` folder, which will make there way on to the website. At which point, I'll disable the feature.

This was a really useful, at times painful (haha), exercise. But I walked away realizing I have to improve my git habits. 

Appreciate you lighting the fire here.

**Comment by seangwright** [comment]
Yes, it's wonderful. Thank you for adding it 🙏.
