### ISSUE TITLE
falcoframework.com is down

### ISSUE THREAD

**Issue by tnishimura** [pimbrouwers/Falco#104]
Not sure if this is the right place for this, but falcoframework.com is down. Not a DNS issue because the 404 message is from GH. 

![image](https://user-images.githubusercontent.com/519704/211234944-477a0397-cb18-4412-bc47-aa46c7669c59.png)

**Comment by pimbrouwers** [comment]
Thanks for pointing this out. The custom domain setting got erased for some reason. Anyway, should be back up now.
