### ISSUE TITLE
Make Falco.Markup optional / pluggable / replacable

### ISSUE THREAD

**Issue by pkese** [pimbrouwers/Falco#117]
I really like Falco, but prefer to use Feliz.ViewEngine style html rendering instead of Falco.Markup (I'm used to Feliz from frontend and I'd like to use it on backend as well to reduce surface area).

Would it be possible to split `Falco.Markup` out completely, so that if it isn't explicitly installed as a package, it doesn't pollute the namespace. Currently `Falco.Markup` is pulled in unconditionally:

https://github.com/pimbrouwers/Falco/blob/a2ff74f8db808c14a40dd5e98c42027320e7d0ef/src/Falco/Response.fs#L10

If it was optional, then one could supply their own `response.ofHtml` that would let them render their own document type (rather than just Falco.Markup). https://github.com/pimbrouwers/Falco/blob/a2ff74f8db808c14a40dd5e98c42027320e7d0ef/src/Falco/Response.fs#L167

**Comment by pimbrouwers** [comment]
Hey Peter,

Thanks for reaching out.

When the Markup module was broken out, my number 1 goal was to ensure backward compatibility with the API at the time (which remains today). With that in mind, this concept isn't possible. I tried, trust me.

But that said, it costs you virtually nothing (we're talking kilobytes in your final DLL or exe), and I'm not sure it's inclusion in the Response and Xss modules is "polluting the namespace". 

I don't see it as a problem in any way to just include & use whatever view engine you'd like :)

**Comment by pkese** [comment]
Ok. I added extra rendering to response and it works fine. Sorry for the inconvenience.

BTW, thanks for the wonderful library, it's really clean and concise ... no new operators and at just the right level of abstraction. Brilliant!

**Comment by pimbrouwers** [comment]
No bother whatsoever. It grinds me that I wasn't able to achieve this 2 yrs
ago.

I am so glad you like it! I find it a nice tribute to ASPNET. Gabe us the
minimal API feel before we had minimal APIs officially!
