### ISSUE TITLE
Docs Website

### ISSUE THREAD

**Issue by AngelMunoz** [pimbrouwers/Falco#12]
Would you be interested in some static website documentation 😁?
something like [this](https://github.com/AvaloniaCommunity/Avalonia.FuncUI.Docs) it's basically a Fornax "blog"

my UI design skills are atrocious as you can see but I can help you setting it up and pushing content if you like the idea

**Comment by pimbrouwers** [comment]
Hello again! 

Excellent idea. Read my mind.

My goal was to eventually have a static docs website. My colleague has been working on a logo for a few weeks. Once he's done I was thinking we could begin work on it? For a first iteration, I think we could simply have a single-pager built off the README. 

Right now, my focus is on getting things to a stable v1.0.0 (non-alpha). So if you're game to help, I'd love some feedback on how it feels to use the framework to build a website. I'm in the middle of building a little side project to smoke test everything in a "true" way. Currently porting it from Giraffe. Will share once I've deployed it!

**Comment by AngelMunoz** [comment]
>My goal was to eventually have a static docs website. My colleague has been working on a logo for a few weeks. Once he's done I was thinking we could begin work on it? For a first iteration, I think we could simply have a single-pager built off the README.

Sure, sounds great I'll try to have something this week

>So if you're game to help, I'd love some feedback on how it feels to use the framework to build a website.

Usually, I just work with JSON API's but I think I can try to build a website with server HTML and stuff like that


Also... something that I've seen it helps a lot is having `dotnet templates` but I think these can be tracked a separate issue if you are interested I can also take a jab at those in the next week

**Comment by pimbrouwers** [comment]
I was thinking a gh-pages + Jekyll off the readme would suffice here. I'm hoping to have the logo in a few weeks. 

Sorry! I should've chosen my words more carefully. An API would serve as a good test as well. The view engine is so well tested (and so easily tested) that I'm confident it's production ready minus any missing tags/attributes.
