### ISSUE TITLE
Falco v5 Routing Bug (Multiple verbs for the same route)

### ISSUE THREAD

**Issue by sheridanchris** [pimbrouwers/Falco#126]
When defining multiple handlers (ex: one for GET, one for POST) for the same endpoint... the first handler is always executed.

To reproduce:

```fsharp
let endpoints = [
    all "/test" [ 
        POST, Response.ofPlainText "POST"
        GET, Response.ofPlainText "GET"
    ]

    post "/test2" (Response.ofPlainText "POST")
    get "/test2" (Response.ofPlainText "GET")
]
```

Sending a GET request to `/test` and `/test2` will return a plain-text response with the value of `"POST"`.

Version: `5.0.0-alpha1`

**Comment by pimbrouwers** [comment]
Interesting. It looks like, as your PR shows, that the httpmetadata code was removed. 

It exists in master: https://github.com/pimbrouwers/Falco/blob/25d828d832c0fde2dfff04775bea1eced9050458/src/Falco/Routing.fs#L24

It disappeared during this commit:
https://github.com/pimbrouwers/Falco/commit/bc6cb4ae726f8359f6d6741e65be61c3294ad14b#diff-90972087cc4ae05d947b8f13c6228e7e07d9753d490febeb714847a9a6da11e3

The best I can reason is that I accidentally removed it.  

Thanks for spotting this and submitting the PR.

**Comment by pimbrouwers** [comment]
#127
