### ISSUE TITLE
5.0.0 RouteEndpoint.Order

### ISSUE THREAD

**Issue by haodeon** [pimbrouwers/Falco#128]
In 5.0.0 the `Order` of endpoints has changed from being a value of 0 to an incrementing value starting at 1.

When using Yarp with Falco, the change in behaviour causes matching routes in Yarp to have a higher precedence than Falco endpoints, bypassing route template precedence.

Adding `Order` to Yarp's configuration solved the issue in my case. This could be hard to manage or even not work if there are complex route templates or a large number of routes to manage.

**Comment by pimbrouwers** [comment]
Hi haodeon, thanks for reaching out.

This is interesting. You're exactly right, I added an explicit order to the endpoints in version 5. I assumed doing that was more adherent to the behaviour expected, not only from library consumers but also client code.

I'm not exactly sure how to handle this. Part of me thinks, we can just set it back to 0. Let route specificity handle things like it was in version 4. But I'm worried that we're missing something in just blindly doing that.

For what it's worth, all tests are green across the board reverting to 0. Then again, I wouldn't necessarily say there is an explicit test case for route order testing.

**Comment by pimbrouwers** [comment]
Thanks for following up so quickly.

I spent so much time review the aspnetcore source code. I don't exactly recall my rationale at the time, but it was likely based upon how I was seeing the endpoint data sources implemented in the core codebase. 

Based on the docs, I think we set back to 0 and support per-route order number setting via the new `HttpEndpoint` field (`Configure : EndpointBuilder -> EndpointBuilder`). I'm thinking like `Routing.setOrder (n : int)`?

**Comment by pimbrouwers** [comment]
Thanks again for discovering this quirk in the alpha build. I can't tell you how much I appreciate it.

I've modified the code to accommodate the changes discussed, you can see it here if you're interested:
https://github.com/pimbrouwers/Falco/commit/2b1d7bd8f25825e4e932242c5b026b583cf3b687

I also just pushed 5.0.0-alpha5 with this code in it.

Cheers!

**Comment by haodeon** [comment]
Thanks for making the change so quickly.

I installed alpha5 and tested it out. It worked great, just like before.

Making route `Order` configurable is a great addition.

As a bonus, I learnt something from your changes too.

Closing issue as it's resolved, cheers!

**Comment by pimbrouwers** [comment]
Thank you. This made my day. I really appreciate your help and interest in the project. Look forward to crossing paths again!
