### ISSUE TITLE
OpenAPI documentation

### ISSUE THREAD

**Issue by brettrowberry** [pimbrouwers/Falco#18]
Is there a way to integrate OpenAPI docs, like say Swashbuckle?

**Comment by pimbrouwers** [comment]
Falco is a minimalistic wrapper atop ASP.NET core. So plugging in OpenAPI would be akin to how you'd use it in a standard web project.

**Comment by brettrowberry** [comment]
That’s good news! I know endpoint routing is what Giraffe needs to get this working, but Falco is already there! If you get around to including an example in your docs, that would be awesome. I’ll try to get PR in.

**Comment by pimbrouwers** [comment]
Not a user of OpenAPI, so I didn't know that! But you hit the nail on the head, Falco wraps Endpoint Routing, so if this package relies on that, it will be a breeze. I would welcome a PR with a sample and updated README.

**Comment by pimbrouwers** [comment]
@brettrowberry any progress on this?

**Comment by brettrowberry** [comment]
Here’s some bad news
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1306

**Comment by pimbrouwers** [comment]
Hey! So we're waiting on them to true up with netcore3?

**Comment by brettrowberry** [comment]
I thought they were autodiscovering routes like they do with controllers, but that doesn’t seem to be the case.

**Comment by panesofglass** [comment]
I'm about to go to town adding the Open API documentation hooks in the soon-to-be Falco.Resource plugin. I'll add the top-level doc bits to the WebHostBuilder once that's all integrated.
