### ISSUE TITLE
Resource builder?

### ISSUE THREAD

**Issue by panesofglass** [pimbrouwers/Falco#19]
How do you feel about providing a [resource builder](https://github.com/panesofglass/frank/blob/aspnetcore3.1/src/Frank/Builder.fs#L17-L208)?

**Comment by pimbrouwers** [comment]
I thought long and hard about adding something like this. Basically a way to plug in a "group" of handlers that would form a REST unit for a specific resource (i.e. `/user`). But to me, it feels too much like a pattern and not enough like core functionality (in this next commit, I'm also removing form streaming functionality for this same reason). 

The philosophy of this library is to provide _only_ the utility required to build a "complete" server-side application. It's difficult to draw a line around what "complete" means in this case. But to this point, I've seen it as: 

- [x] Build & run self-host mechanism
- [x] Handle routing
- [x] Process requests
- [x] Model binding
- [x] Render text
- [x] Render markup (html, svg, xml)
- [x] Render JSON
- [x] Authentication & Authorization

With that said, I think there is tremendous utility to these type of tools. So I wonder if we handle this by creating sub-packages, for example `Falco.ApiBuilder` and `Falco.MultipartStreaming`? This allows the core package to be light and clean, and enables incremental enhancement. We'd also have to decide at that point whether we should house all of this under an organization account?

**Comment by panesofglass** [comment]
Sounds good. My more recent goal with Frank was to redo Freya directly on top of ASP.NET Core. Maybe Falco.WebMachine? :)

**Comment by panesofglass** [comment]
How about I start be replacing the WebHostBuilder in Frank with the one from Falco, then we work it in, if we want, from there?

**Comment by pimbrouwers** [comment]
That sounds like an excellent idea! I'm really looking forward to merging our efforts. And I appreciate that you're open to doing it under the "Falco" umbrella :)

**Comment by panesofglass** [comment]
Well, Frank no longer has any brand value, and it is so far from Sinatra at this point, I don’t see the point of the name. Besides, all these separate but similar packages make it harder to get started.

**Comment by panesofglass** [comment]
I've got the WebHostBuilder in Frank matching roughly with yours. Next step is to replace it. See anything in mine that might be worth pulling over before I make the swap?

**Comment by pimbrouwers** [comment]
I'm open to ideas! I feel like I've covered all the different intersection.
But if I've missed anything let me know.

I was contemplating cleaning up the route operations yesterday. Reducing
them to a single "route" operator (already exists) which accepts a verb,
instead of named operators for each method. Thoughts?
