### ISSUE TITLE
Question: why another F# view engine?

### ISSUE THREAD

**Issue by panesofglass** [pimbrouwers/Falco#20]
Out of curiosity, why does this project contain another F# view engine? In other words, how does this one differ from the ones in Fable, Giraffe, etc.?

**Comment by pimbrouwers** [comment]
This whole thing started as an intellectual experiment and evolved into a
workable solution. When I finally decided to package this, I saw the view
engine as a core feature. Thus, not something I wanted to make an external
package.

As far as differences, I can only speak to Giraffe, which uses a
StringBuilder approach. Whereas Falco uses string list concatenation.

**Comment by panesofglass** [comment]
Thanks!

**Comment by pimbrouwers** [comment]
No sweat my man!
