### ISSUE TITLE
Any template engine integration?

### ISSUE THREAD

**Issue by rishavs** [pimbrouwers/Falco#26]
Hey Pim

are there any plans for integrating with a template engine?
A lot of my frontend work is just copy paste from various sites and having support for html syntax would be great.

**Comment by pimbrouwers** [comment]
Hey @rishavs, thanks for reaching out. 

I hadn't planned on doing this, since it ultimately involves reflection. 

If it's purely a piece of static HTML then you could use `Markup.Text.raw` to render it
