### ISSUE TITLE
Feature requests or breaking changes for Falco v3.x.x

### ISSUE THREAD

**Issue by pimbrouwers** [pimbrouwers/Falco#28]
With .NET 5.0 finally here, it seems like a good time to begin exploring v3.x.x which will support both the `netcoreapp3.1` and `net5.0` build targets.

In saying that, this is a great opporunity to include any new features and/or breaking changes to the API. Included so far:
- Removal of the `[<AutoOpen>]` attribute in the routing module to prevent polluting the global scope
- Addition of "multi-method" endpoints
- ~Validation module~

So, if you're a user of Falco and you have some ideas, I want to hear from you!

**Comment by pimbrouwers** [comment]
# Additional Changes

Removals:
- `type ExceptionHandler`
- `type ExceptionHandlingMiddleware`
- `Host.defaultExceptionHandler`
- `Host.defaultNotFoundHandler`
- `Host.startWebHostDefault`
- `IApplicationBuilder.UseHttpEndpoints (endpoints : HttpEndpoint list)` 
    - replaced by `IApplicationBuilder.UseFalco (endpoints : HttpEndpoint list)`

Additions:
- `IServiceCollection.AddFalco ()` 
- `IServiceCollection.AddFalco (routeOptions : RouteOptions -> unit)` 
- `IApplicationBuilder.UseFalco (endpoints : HttpEndpoint list)`
- `IApplicationBuilder.UseFalcoExceptionHandler (exceptionHandler : HttpHandler)`

**Comment by AngelMunoz** [comment]
I'm thinking something like this can be helpful for the REST API cases, not sure if you find it worth for the `Response.*` functions

```fsharp
let requiresAuthentication (successHandler: HttpHandler) (failedAuthHandler: string -> HttpHandler) =
        fun (ctx: HttpContext) ->
            task {
                if Falco.Security.Auth.isAuthenticated ctx
                then return! successHandler ctx
                else return! failedAuthHandler "Authentication Failed" ctx
            }
```
any thoughts?

**Comment by pimbrouwers** [comment]
@AngelMunoz plop this into your project and see if it helps you:

```fsharp
module Request = 
    let ifAuthenticated 
        (handleAuthenticated : HttpHandler)
        (handleNotAuthenticated : HttpHandler) : HttpHandler =
        fun ctx ->
            if Auth.isAuthenticated ctx then handleAuthenticated ctx
            else handleNotAuthenticated ctx
```
