### ISSUE TITLE
How to debug it on Visual Studio?

### ISSUE THREAD

**Issue by arthur-s** [pimbrouwers/Falco#44]
I'm new to F#. I've setup VS code with Ionide, it works well.
But I also would like to try Visual Studio, and can't connect it with Falco for debugging (server doesn't start), could you help please?

**Comment by pimbrouwers** [comment]
Hiya Arthur!

Debugging with visual studio should be as simple as pressing F5.

I would make sure you're using the latest version of Visual Studio 2019, which will ensure you also have the latest version of the runtime and SDK installed.

**Comment by arthur-s** [comment]
ahh, I wrongly chose project type. Now I've opened it as a web project, and all works fine. Thanks!
