### ISSUE TITLE
Question: How to do routing on a multilingual site?

### ISSUE THREAD

**Issue by bytesource** [pimbrouwers/Falco#50]
Hi Pim, 

After Ben Gobeil's great introduction to Falco (https://www.youtube.com/watch?v=DTy5gIUWvpo), I decided to take a closer look at your repo. 

I especially liked your blog example where you use markdown and YAML frontmatter for the content (https://github.com/pimbrouwers/Falco/tree/master/samples/Blog). This approach might be a good way to convert a tiny PHP site of mine (http://www.zp-tec.com) and use it a training ground to sharpen my F# skills.

OK, now to my question:

The new version of my site will be multilingual, so all URLs of the second language have to be prefixed the with country code like this: /**<country_code>**/path/to/slug/. 

How do I do this with Falco? Do I need to add the prefix to every slug manually, or is there some concept of nested routing like in Saturn? Or any other way to deal with multilanguage URLs?

For example, Saturn has something like nested routes (https://saturnframework.org/explanations/routing.html), but Falco's `route` and `all` functions in `Routing.fs` don't seem to have this feature.

I also read Microsoft's article about endpoint routing you link to on your README page, but couldn't find a solution there either. That said, although I feel more and more comfortable programming in F#, I've never done anything with ASP.NET.

Have a good day!

Stefan

**Comment by pimbrouwers** [comment]
Hi Stefan!

I appreciate you reaching out very much. Equally excited for your journey into F#. There will be challenges, at least there was for me, but it is worth it.

As to you question, boy is it a goody! I have been wracking my brain as to how I wanted to recommend doing this. Here is the best I've come up with so far. Bear in mind I wrote this in notepad haha!

```fsharp
type Country =
	| Canada 
	| China
	| Netherlands
	// etc.

//
// Handlers
let bookDetailsHandler (country : Country) : HttpHandler = //...

let authorDetailsHandler (country : Country) : HttpHander = //...

//
// Router

let createEndpoints (routes : (string * (HttpVerb * HttpHandler) list) list) =
    [ for (route, endpoints) in routes -> 
        all route endpoints ]

let withCountry (next : HttpHandler) : HttpHandler =
	let routeBinder (r : RouteCollectionReader) =
		match r.TryGetString "country" with
		| "CAN" -> Ok Canada
		| "CHN" -> Ok China
		| "NED" -> Ok Netherlands
		| _ -> Error "Country not found"

	let notFound message : HttpHandler = 
		Response.withStatusCode 404
		>> Response.ofPlainText message

	Request.bindRoute routeBinder next notFound

let endpoints = 
	[ "/{iso3}/Book/Details/{id}", [
		GET, bookDetailshandler ]

	  "/{iso3}/Author/Bio/{id}", [ 
	  	GET, authorDetailsHandler ] 
  	]
	|> createEndpoints
```

**Comment by bytesource** [comment]
Hi Pim, 

Thank you so much for thinking about how to handle on a multilingual site! Having looked at the Falco and Validus source code, I really like your clean coding style.

I've started using Falco in a small project, where I need to download, validate and transform order data from a webhook and send it to a warehouse. This way I get a better understanding of Falco and can implement what I read in "Domain Modeling Made Functional".

One last question: Have you heard about source linking (https://github.com/dotnet/sourcelink)? I downloaded the Falco repo, so I can jump to an implementation of a function, but it would be great if I could do the same from within a project that uses Falco.

Keep up the great work!

Stefan

**Comment by pimbrouwers** [comment]
My pleasure! I really do appreciate you saying that and I'm glad you enjoy the libraries!

That is an absolutely fantastic idea. Want to do a PR so you get credit?

**Comment by bytesource** [comment]
Hi Pim, 

It seems that for projects that are hosted on Github, these setting would need to be added to the fsproj file:
https://github.com/dotnet/sourcelink#using-source-link-in-net-projects
https://github.com/dotnet/sourcelink#githubcom-and-github-enterprise

```
<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup>
    <TargetFramework>netcoreapp3.1;net5.</TargetFramework>
 
    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
 
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/> 
  </ItemGroup>
</Project>
```

But as I haven't published a package to NuGet, I don't quite understand these parts:
**1)** The optional lines from the code above: 


    
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
 
    
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  
    
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>


**2)** This paragraph from the README:

> If you distribute the library via a package published to NuGet.org, it is recommended to build a symbol package and publish it to NuGet.org as well. This will make the symbols available on NuGet.org symbol server, where the debugger can download it from when needed. Alternatively, you can include the symbols in the main package.

I found one package that is using source links, and that is Farmer: https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Farmer.fsproj

It's a long project file, so I tried to extract the relevant parts:

https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Farmer.fsproj#L29

```
<PropertyGroup>
<!-- SourceLink settings -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
</PropertyGroup>
```

https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Farmer.fsproj#L41

```
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="5.0.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
  </ItemGroup>
```

Also, the following setting was not mentioned in the source link README, but might be related, so I put it here for reference.
https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Farmer.fsproj#L36

```
<!-- Normalize paths to sources in symbols when built in Azure Pipelines -->
  <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
```
