### ISSUE TITLE
Use different port?

### ISSUE THREAD

**Issue by vip-ehowlett** [pimbrouwers/Falco#60]
I was wondering how you configure the host to use a different port? It seems like it would be a useful feature in the CE for webHost.

**Comment by swuecho** [comment]
code from my project:

```
// -----------
// Configure Web host
// -----------
let configureWebHost (endpoints: HttpEndpoint list) (webHost: IWebHostBuilder) =
    webHost
      //  .ConfigureServices(configureServices)
      //  .Configure(configureApp endpoints)
        .UseUrls([| sprintf "http://0.0.0.0:%s" Config.serverPort |])

[<EntryPoint>]
let main args =
    webHost args {
        configure configureWebHost
       ....
```

**Comment by ImaginaryDevelopment** [comment]
I'm confused how to use this with the non-builder format. I tried following the example from https://www.falcoframework.com/docs/host-configuration.html to figure how to plug in your `configureWebHost` method, primarily since it seems none of the documentation examples are using that format
