### ISSUE TITLE
Errors in Tutorial?

### ISSUE THREAD

**Issue by r4mp4l** [pimbrouwers/Falco#67]
Hello,

I am following the steps here: https://www.falcoframework.com/#getting-started

I run the following steps:
1.  dotnet new -i Falco.Template::3.0.0
2. dotnet new falco -o HelloWorldApp

I get this error message

`PS C:\Users\grampal\Documents\Programming\FSharp\FalcoStuff> dotnet new falco -o HelloWorldApp
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "Falco" (falco) from author "Pim Brouwers, Daniel Tuna and contributors" in pack Falco.Template
    To use this template, run the following command and try again:
        dotnet new -i Falco.Template::3.0.0`

I have tried VSCode and Visual Studio as well.

Please help.

**Comment by ilog2000** [comment]
This line works for me:
```shell
dotnet new -i "Falco.Template::3.0.0"
```

**Comment by r4mp4l** [comment]
The next line doesn't work "dotnet new falco -o HelloWorldApp"

```
dotnet new falco -o HelloWorldApp    
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "Falco" (falco) from author "Pim Brouwers, Daniel Tuna and contributors" in pack Falco.Template
    To use this template, run the following command and try again:
        dotnet new -i Falco.Template::3.0.0
```

**Comment by ilog2000** [comment]
I've just tried - the next line works here as well. Something is wrong with NuGet on your side. Try maybe
`dotnet new -i "Falco.Template::3.0.0"  --debug:reinit`

**Comment by r4mp4l** [comment]
Thank you for your suggestion. I tried the re-init and it doesn't work. 

Can someone suggest an online IDE for Falco?

**Comment by metatron-the-chronicler** [comment]
> Thank you for your suggestion. I tried the re-init and it doesn't work.
> 
> Can someone suggest an online IDE for Falco?

You may need to update your version of dotnet. Running it on version 5 produced the same error for me. Updating to 6.0.301 resolved the issue for me.

**Comment by pimbrouwers** [comment]
Did you get this going @r4mp4l?
