### ISSUE TITLE
Add dapper

### ISSUE THREAD

**Issue by rodrigodevelms** [pimbrouwers/Falco#68]
Hello guys. 
I'm having trouble adding Dapper to Falco.
Do you have any code example?

**Comment by pimbrouwers** [comment]
Hi! Thanks for reaching out.

Falco imposes no constraints on how you handle I/O, like database workloads. So it is entirely up to you.

Obviously, the actual command/query will occur within a handler, and after any route/query/form mapping. Async is probably not a bad idea, but not strictly necessary.

Do you have any code to share? If so, I can offer some more specific recommendations.

I did blog a little about data access, which you can read this post: https://www.pimbrouwers.com/2020/12/08/fsharp-on-the-web-a-guide-to-building-websites-with-falco-dotnet-x-and-aspdotnet-core.html

The library used in that post is Donald, another of mine, but the concepts will translate.
