### ISSUE TITLE
MapJson doesn't work

### ISSUE THREAD

**Issue by BashkaMen** [pimbrouwers/Falco#84]
https://github.com/pimbrouwers/Falco/blob/master/src/Falco/Request.fs#L302
you forgot to call next

**Comment by BashkaMen** [comment]
maybe bad merge

**Comment by pimbrouwers** [comment]
Totally was. Apologies for that. I've pushed 3.1.14, should be available momentarily. I imagine this will be the final patch of version 3. I am hoping to have version 4 available in beta this week.

Thanks again for pinging me.
