### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by ShalokShalom** [pimbrouwers/Falco#87]
Clicking on the first random link, dead:

There are dead link checkers. It looks very unprofessional for a web framework, it your own webpage is not even able to maintain links. 

Dead Link: https://github.com/pimbrouwers/Falco/tree/master/docs/en/markup.html

```
https://www.falcoframework.com/ 

Key features:
Native F# view engine.
```

**Comment by bytesource** [comment]
@ShalokShalom 
I sometimes have dead links on my website that I'm making money from. It happens, and maintaining a project, is a lot of work. 

If you could drop a link to a link checker you like that would be very helpful.

**Comment by ShalokShalom** [comment]
![Screenshot_20221013-111122](https://user-images.githubusercontent.com/6344099/195555882-b816cedc-3879-44e0-84d7-92cc393a3e8f.png)

https://www.deadlinkchecker.com/

I also looked for solutions, which you could just implement.

I wonder why, but it seems like there is not a single maintained library. 

Although, here is a stackoverflow:

https://stackoverflow.com/a/73201829/6712414

Maybe make that a feature request?

**Comment by bytesource** [comment]
That's terrific! Thanks a lot for checking the site.

**Comment by pimbrouwers** [comment]
Thanks for reaching out, and I apologize for any inconvenience.

This is entirely my fault. I pushed the dev branch into master a few weeks
ago in anticipation of releasing v4 shortly thereafter. But I had some
personal matters come up that have completely soaked up my personal time.

So right now, the repo, site and package are in a confusing state. For
example there are still several documents missing from the new website, and
the latest v4 package is still beta.

In saying that, please do remember that I have a family and a full-time
job, that take priority over this when s*** hits the fan.

I appreciate the effort to find these broken links, and run the link
checker.

Anyway, I am hoping to have all of this settled this week. Thanks again.

**Comment by seangwright** [comment]
I've been reading through some of the documentation and I just wanted to drop a note that this link https://www.falcoframework.com/docs/host.html#custom-services also doesn't go to any section on that page.

No rush, just a heads up.

**Comment by JulesNP** [comment]
This page also seems to be missing: https://www.falcoframework.com/docs/model-binding.html
