### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by brettrowberry** [pimbrouwers/Falco#91]
There’s a typo in a link on https://www.nuget.org/packages/Falco/4.0.0

> Uniform API for [accessing request data](https://github.com/pimbrouwers/Falco/tree/master/doc/re uest.md).

**Comment by brettrowberry** [comment]
Sorry, I didn’t fix it myself, I was just on my phone.

**Comment by pimbrouwers** [comment]
Don't be!
