### ISSUE TITLE
Question: XSS vs CSRF

### ISSUE THREAD

**Issue by Banashek** [pimbrouwers/Falco#93]
Hello, what follows is just a **nitpick** from browsing the code. **Feel free to disregard and close** if it's not relevant. 

I was having a look at the library and noticed that the namespace handling AntiForgeryTokens was named "XSS".
Most of the time I see such a module named something to do with CSRF rather than XSS, since the responsibility of the AntiForgeryTokens is to prevent Cross-Site Requests. While Cross-Site Requests could be triggered by an XSS attack triggering an ajax form request, the scope of XSS is much more broad in it's scope (reflected vs stored vs DOM), and the defenses have more to do with output sanitization/encoding ("safe sinks") rather than input origin verification.

**Comment by seangwright** [comment]
In the past instead of CSRF I would see with XSRF and then I'd accidentally confuse that with XSS. Maybe that happened here?
