### ISSUE TITLE
Falco 4 handler not responding correctly. 

### ISSUE THREAD

**Issue by sheridanchris** [pimbrouwers/Falco#94]
When doing handler composition, there seems to be a regression in Falco 4 which causes the handler to not respond correctly (200 OK with empty body). This however, works as expected in Falco 3

You can view a repro here: https://github.com/sheridanchris/FalcoRepro

You'll notice in the repro there's a `do! Task.Delay(...)` in both versions. If you remove this from the Falco 4.0 version it seems to work fine (if that gives you any hints).

**Comment by seangwright** [comment]
@sheridanchris I noticed this same behavior when doing async/Task work with [Request.mapForm](https://github.com/pimbrouwers/Falco/blob/master/src/Falco/Request.fs#L131) in v4.0.

You can see in [this discussion](https://github.com/pimbrouwers/Falco/discussions/90#discussioncomment-4124848) how I had to adopt a different approach (lower-level) to compose my async work with the APIs Falco provides.

Here's [two approaches](https://github.com/NitroDevs/FShopOnWeb/blob/main/src/Microsoft.eShopWeb.Web/Basket/Basket.Page.fs#L39) I ended up trying that both work.

#### Approach 1 - `Request.mapFormAsync`

```fsharp
  let post: HttpHandler =
    Services.inject<ShopContext> (fun db ->

      let mapAsync = fun (form: FormCollectionReader) ->
        form.TryGetGuid "id"
        |> BasketDomain.updateBasket db 1
        |> Async.StartAsTask

      Request.mapFormAsync mapAsync (fun quantity ->
        match quantity with
        | None -> Response.redirectPermanently "/basket?error=notfound"
        | Some q -> Response.redirectPermanently $"/basket?added={q}"))
```

where `Request.mapFormAsync` was something I added:

```fsharp
module Request =
  open System.Threading.Tasks
  open Microsoft.AspNetCore.Http
  open Falco

  let mapFormAsync
    (mapAsync : FormCollectionReader -> Task<'T>)
    (next : 'T -> HttpHandler) =
    fun (ctx: HttpContext) -> (task {
      let! form = Request.getForm ctx
      let! res = mapAsync form
      return! next res ctx
    }:> Task)
```

#### Approach 2 - `Request.getForm`

```fsharp
  let postAlternate: HttpHandler =
    Services.inject<ShopContext> (fun db -> fun ctx ->
      task {
        let! form = Request.getForm ctx

        let productId = form.TryGetGuid "id"

        let! quantity = BasketDomain.updateBasket db 1 productId |> Async.StartAsTask

        return!
          match quantity with
          | Some q -> Response.redirectPermanently $"/basket?added={q}" ctx
          | None -> Response.redirectPermanently "/basket?error=notfound" ctx
      })
```

**Comment by sheridanchris** [comment]
@seangwright Thanks for the feedback and suggestions. I'll make sure to try this out ASAP.

**Comment by pimbrouwers** [comment]
I just rolled out a fix for this. Huge shoutout to @mlaily for the discovery.
